### PR TITLE
composer: use "self.version", fix psr-0 prefix

### PR DESCRIPTION
**Pull request by glensc**
please also release 2.5.9 so this could be used via composer

### CODE REVIEW

**Comment by yunosh** [comment]
composer.json is actually generated automatically from .horde.yml with the horde/components tool, so these changes would be overwritten on each release.
Any why use self.version? It would replace *any* PEAR-packaged version of this library.

**Comment by glensc** [comment]
no, `self.version` will not replace any version. why you say that? if package version is `1.2.3`, then self.version is `1.2.3`, so it will replace `1.2.3`

it's rather your glob `2.*` will match multple versions, `self.version` will replace single version.

see real life example:
- https://github.com/symfony/symfony/blob/v4.2.4/composer.json#L37-L90

**Comment by glensc** [comment]
there's nothing in horde.yaml about fixing the psr-0 classpath, so you need some other way to find a way to provide it, or fix generator, or add override support.

**Comment by yunosh** [comment]
> no, `self.version` will not replace any version. why you say that? if package version is `1.2.3`, then self.version is `1.2.3`, so it will replace `1.2.3`
> 
> it's rather your glob `2.*` will match multple versions, `self.version` will replace single version.

Exactly. And that's the intention.

**Comment by yunosh** [comment]
> there's nothing in horde.yaml about fixing the psr-0 classpath, so you need some other way to find a way to provide it, or fix generator, or add override support.

Correct.

**Comment by yunosh** [comment]
Fix needed in horde/horde-components

**Comment by glensc** [comment]
not only, the package is not registered in packagist.org!

**Comment by yunosh** [comment]
All our libraries are going to be released on Packagist, once the composer.json generation is stable. No need for PRs for individual libraries.

**Pull request closed without merging**
